
#define DEF_DYNAMICOBJECT_FIRE			1
#define DEF_DYNAMICOBJECT_FISH			2
#define DEF_DYNAMICOBJECT_FISHOBJECT	3
#define DEF_DYNAMICOBJECT_MINERAL1		4
#define DEF_DYNAMICOBJECT_MINERAL2		5
#define DEF_DYNAMICOBJECT_ARESDENFLAG1	6
#define DEF_DYNAMICOBJECT_ELVINEFLAG1	7
#define DEF_DYNAMICOBJECT_ICESTORM		8
#define DEF_DYNAMICOBJECT_SPIKE			9
#define DEF_DYNAMICOBJECT_PCLOUD_BEGIN	10
#define DEF_DYNAMICOBJECT_PCLOUD_LOOP	11
#define DEF_DYNAMICOBJECT_PCLOUD_END	12
#define DEF_DYNAMICOBJECT_FIRE2			13
#define DEF_DYNAMICOBJECT_FIRE3			14 // Snoopy, for FireBow

